# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Contour News 
email: heroes@countournews.com
description: > # this means to ignore newlines until "baseurl:"
  We are the next generation of storytellers.  
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: contournews
github_username:  # leave blank for now

# Build settings
markdown: kramdown
